name: "[My UIViews]"
title: "[My UIViews]"
highlighter: rouge
paginate: 10
paginate_path: "page:num"
#safe: true
url: http://www.myuiviews.com
author: "William Welbes"
plugins: [jekyll-paginate]

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge